[rewrite_local]

# LYS 视频处理
^https?://.*\.(00po|uzrclb-lys)\.shop/api/app/vid/m3u8/.* url script-request-header https://raw.githubusercontent.com/Loukyuu1120/cdn/refs/heads/main/scripts/lys.js

# LYS 广告请求处理
^https?://.*\.(00po|uzrclb-lys|gx2cbflpbt)\.(shop|com)/.* url script-request-header https://raw.githubusercontent.com/Loukyuu1120/cdn/refs/heads/main/scripts/lysad.js

# LYS 广告响应处理
^https?://.*\.(00po|uzrclb-lys|gx2cbflpbt)\.(shop|com)/.* url script-response-body https://raw.githubusercontent.com/Loukyuu1120/cdn/refs/heads/main/scripts/lysad.js


# ========== 广告拦截 ==========

^https?://api-dc-prod-\d+\.cyou/ - reject
^https?://api-dc2-prod-\d+\.cyou/ - reject
^https?://.*\.eqfx9bas\.cc/ - reject
^https?://.*\.yihaici\.(top|com)/ - reject
^https?://.*\.epuf3tk\.cc/ - reject
^https?://[^/]+/upload_01/ads/ - reject

[mitm]

hostname = oihawlma.00po.shop, *.00po.shop, *.oukky-lys.shop, *.cyou, *.eqfx9bas.cc, *.yihaici.top, *.yihaici.com, *.epuf3tk.cc, *.hxscwine.com, *.wdyzdc.com, *.gx2cbflpbt.com, *.uzrclb-lys.shop, *.sqszbrs.live
